### PR TITLE
Fixed JSON column with binlog streamer

### LINKED ISSUE #86: Error 3144: Cannot create a JSON value from a string with CHARACTER SET binary
Moving a shop  failed with
> Error 3144: Cannot create a JSON value from a string with CHARACTER SET binary
error.

### PR DESCRIPTION
**Pull request by shuhaowu**
JSON column was previously being recognized as a []byte array in the BinlogWriter. This causes the INSERT/UPDATE/DELETE query generated to be with something like `_binary'{"data": 1}'`. However, JSON data are not binary, thus MySQL will return errors  errors such as:

> Error 3144: Cannot create a JSON value from a string with CHARACTER SET binary error.

Fixing this requires us to pass the column types into the methods actually escaping the values (`appendEscapedValues`), as we cannot infer that something is a JSON type from the Go type alone. This turned out to be a rather large list of methods.

To do this the most generic way, I just pass down the table columns all the way (in case we need something else from it in the future).

Fixes #86.

### CODE REVIEW

File: dml_events.go [hunk 1]
```diff
@@ -253,84 +250,77 @@ func NewBinlogDMLEvents(table *schema.Table, ev *replication.BinlogEvent, pos my
 	}
 }
 
-func loadColumnsForTable(table *schema.Table, valuesToVerify ...RowData) ([]string, error) {
```
Comment (shuhaowu) [inline dml_events.go]: Since I'm passing down `[]TableColumn` anyway, I might as well just do the column name quoting in the (`build*` methods that actually builds the query).

This method is a bit vague on what it does anyway, so I removed it.

File: dml_events.go [hunk 2]
```diff
@@ -253,84 +250,77 @@ func NewBinlogDMLEvents(table *schema.Table, ev *replication.BinlogEvent, pos my
...
-	for _, values := range valuesToVerify {
-		if err := verifyValuesHasTheSameLengthAsColumns(table, values); err != nil {
```
Comment (shuhaowu) [inline dml_events.go]: This method is now instead called manually in the `AsSQLQuery` methods directly.

File: dml_events.go [hunk 3]
```diff
@@ -433,8 +423,12 @@ func appendEscapedString(buffer []byte, value string) []byte {
...
 }
 
-func appendEscapedBuffer(buffer, value []byte) []byte {
-	buffer = append(buffer, "_binary'"...)
+func appendEscapedBuffer(buffer, value []byte, binary bool) []byte {
+	if binary {
+		buffer = append(buffer, "_binary"...)
+	}
+
+	buffer = append(buffer, '\'')
```
Comment (milanatshopify) [inline dml_events.go]: I'm definitely stretching my ability to review this, but why do we need this extra ' here?

Comment (shuhaowu) [reply dml_events.go]: This was in there previously as `_binary'`, as we still need to quote the data. It is just split now depending if you want the binary encoding or not.

File: test/integration/types_test.rb [hunk 4]
```diff
@@ -0,0 +1,43 @@
+require "test_helper"
+
+class TrivialIntegrationTests < GhostferryTestCase
```
Comment (hkdsun) [inline test/integration/types_test.rb]: `TypesTest`

Comment (shuhaowu) [reply test/integration/types_test.rb]: Good catch. Thanks.
